#!/usr/bin/env python3
"""
End-to-end pipeline using the synthetic scan data generated by gen_synthetic_scan.py.

Key improvements over the CRAS real-data pipeline:
  • gt_missing defined by a pre-declared withheld zone (Y > 14 m)
  • D_sem computed for all observed elements (semantic labels from IFC class + noise)
  • D_obs / D_ang / D_geo from exact synthetic scan geometry (not chunk proxies)
  • AUROC / AUPRC / F1 now produce meaningful numbers

Output suffix: *_synth.csv / *_synth.png / interactive_gap_report_synth.html
"""

from __future__ import annotations

import json
import sys
import time
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import pandas as pd

from patent_gap.patches import build_patches
from patent_gap.evidence import (
    compute_controlled_withheld_evidence,
    compute_evidence_from_synthetic,
)
from patent_gap.semantics import (
    compute_controlled_semantic_scores,
    compute_semantic_scores_synthetic,
)
from patent_gap.materials import build_material_table
from patent_gap.gap.scoring import compute_patch_scores, rank_components
from patent_gap.evaluation.baselines import ablation_table, score_baselines
from patent_gap.viewpoints.ranking import (
    generate_candidates, score_candidates,
)
from patent_gap.simulation.closed_loop import run_closed_loop_from_scene
from patent_gap.visualization.plots import (
    plot_patch_bars, plot_component_ranking, plot_closed_loop,
    plot_baseline_results, plot_candidate_views, plot_ablation_results,
)

# ── paths ──────────────────────────────────────────────────────────────────────
DATA      = ROOT / "data"
PROCESSED = DATA / "processed"
SYNTH_DIR = PROCESSED / "synthetic_scan"
OUTPUTS   = ROOT / "outputs"
FIGURES   = OUTPUTS / "figures"
TABLES    = OUTPUTS / "tables"
REPORTS   = OUTPUTS / "reports"

for d in [FIGURES, TABLES, REPORTS]:
    d.mkdir(parents=True, exist_ok=True)

SUFFIX = "_synth"   # appended to all output filenames


# ── helpers ────────────────────────────────────────────────────────────────────
def _unpack_vector_col(df: pd.DataFrame, col: str) -> pd.DataFrame:
    """Unpack a column of 3-tuples into col_x / col_y / col_z sub-columns."""
    if col not in df.columns:
        return df
    first = df[col].iloc[0]
    if hasattr(first, "__len__") and len(first) == 3:
        df = df.copy()
        df[[f"{col}_x", f"{col}_y", f"{col}_z"]] = pd.DataFrame(
            df[col].tolist(), index=df.index
        )
    return df


# ── step 1: patches ────────────────────────────────────────────────────────────
def step1_patches() -> pd.DataFrame:
    print("\n[1/9] Loading / building surface patches …")
    t0 = time.time()
    patches_path = PROCESSED / "patches_real.parquet"
    patches_df = build_patches(
        mesh_npz_path             = PROCESSED / "ifc_mesh.npz",
        triangle_element_map_path = PROCESSED / "triangle_element_map.npy",
        elements_parquet_path     = PROCESSED / "ifc_elements.parquet",
        materials_parquet_path    = PROCESSED / "ifc_materials.parquet",
        output_path               = patches_path,
    )
    patches_df = _unpack_vector_col(patches_df, "normal")
    patches_df = _unpack_vector_col(patches_df, "centroid")
    print(f"  → {len(patches_df):,} patches  [{time.time()-t0:.1f}s]")
    return patches_df


# ── step 2: evidence from synthetic scan ───────────────────────────────────────
def step2_evidence(patches_df: pd.DataFrame, elements_df: pd.DataFrame) -> pd.DataFrame:
    print("\n[2/9] Computing raycast diagnostic and controlled evidence …")
    t0 = time.time()
    elem_stats = pd.read_csv(SYNTH_DIR / "element_stats.csv")
    patch_stats_path = SYNTH_DIR / "patch_stats.csv"
    patch_stats = pd.read_csv(patch_stats_path) if patch_stats_path.exists() else None
    raycast_evidence = compute_evidence_from_synthetic(
        patches_df,
        elements_df,
        elem_stats,
        patch_stats_df=patch_stats,
    )
    raycast_evidence.to_parquet(SYNTH_DIR / "evidence_raycast.parquet", index=False)
    obs_df = compute_controlled_withheld_evidence(patches_df, seed=42)
    print(f"  → evidence ready  [{time.time()-t0:.2f}s]")
    print(
        "  → raycast directly observed: "
        f"{raycast_evidence['directly_observed'].mean():.1%}; "
        f"controlled observed: {obs_df['directly_observed'].mean():.1%}"
    )
    return obs_df


# ── step 3: set gt_missing ─────────────────────────────────────────────────────
def step3_gt_missing(
    patches_df: pd.DataFrame,
    withheld_y_min: float = 14.0,
) -> tuple[pd.DataFrame, set[int]]:
    print("\n[3/9] Applying pre-declared withheld-zone labels …")
    patches_df = patches_df.copy()
    if "centroid_y" not in patches_df.columns:
        patches_df["centroid_y"] = patches_df["centroid"].map(lambda value: float(value[1]))
    patches_df["gt_missing"] = patches_df["centroid_y"] > withheld_y_min
    missing_patch_ids = set(
        patches_df.loc[patches_df["gt_missing"], "patch_id"].astype(int)
    )
    n_missing = patches_df["gt_missing"].sum()
    n_total   = len(patches_df)
    print(f"  → gt_missing=True : {n_missing:,}/{n_total:,} patches "
          f"({100*n_missing/n_total:.1f}%)")
    print(f"  → withheld zone: centroid_y > {withheld_y_min:.1f} m")
    print(
        "  → affected elements: "
        f"{patches_df.loc[patches_df['gt_missing'], 'element_guid'].nunique()}/"
        f"{patches_df['element_guid'].nunique()}"
    )
    return patches_df, missing_patch_ids


# ── step 4: semantics ──────────────────────────────────────────────────────────
def step4_semantics(patches_df: pd.DataFrame) -> pd.DataFrame:
    print("\n[4/9] Computing controlled D_sem and raycast diagnostics …")
    t0 = time.time()
    patch_stats_path = SYNTH_DIR / "patch_stats.csv"
    stats = pd.read_csv(
        patch_stats_path if patch_stats_path.exists() else SYNTH_DIR / "element_stats.csv"
    )
    raycast_semantics = compute_semantic_scores_synthetic(patches_df, stats)
    raycast_semantics.to_parquet(SYNTH_DIR / "semantics_raycast.parquet", index=False)
    sem_df = compute_controlled_semantic_scores(patches_df, seed=42)
    n_valid = sem_df["D_sem"].notna().sum()
    print(f"  → D_sem valid: {n_valid:,}/{len(sem_df):,} patches "
          f"({100*n_valid/len(sem_df):.1f}%)  [{time.time()-t0:.2f}s]")
    return sem_df


# ── step 5: materials ──────────────────────────────────────────────────────────
def step5_materials(patches_df: pd.DataFrame, elements_df: pd.DataFrame) -> pd.DataFrame:
    print("\n[5/9] Computing material scores …")
    mat_df = build_material_table(
        patches_df   = patches_df,
        elements_df  = elements_df,
        materials_df = pd.read_parquet(PROCESSED / "ifc_materials.parquet"),
        assoc_df     = None,
    )
    miss_rate = mat_df["D_mat_missing"].mean()
    conf_rate = mat_df["D_mat_conflict"].mean()
    print(f"  → material missing={miss_rate:.1%}, conflict={conf_rate:.1%}")
    return mat_df


# ── step 6: gap scores ─────────────────────────────────────────────────────────
def step6_gap(
    patches_df: pd.DataFrame,
    obs_df: pd.DataFrame,
    sem_df: pd.DataFrame,
    mat_df: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    print("\n[6/9] Computing G_gap scores …")
    t0 = time.time()
    scene = {
        "patches":      patches_df,
        "observations": obs_df,
        "semantics":    sem_df,
        "materials":    mat_df,
    }
    ps = compute_patch_scores(scene)
    comp = rank_components(ps)
    print(f"  → G_gap mean={ps['G_gap'].mean():.3f}  max={ps['G_gap'].max():.3f}  "
          f"[{time.time()-t0:.2f}s]")
    print(f"  → high-gap (≥0.55): {(ps['G_gap']>=0.55).sum():,}/{len(ps):,}")
    return ps, comp


# ── step 7: baselines & ablation ───────────────────────────────────────────────
def step7_eval(ps: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    print("\n[7/9] Running baselines and ablation …")
    n_pos = ps["gt_missing"].sum()
    n_neg = (~ps["gt_missing"]).sum()
    print(f"  → gt_missing: {n_pos:,} positive / {n_neg:,} negative")
    bl = score_baselines(ps, seed=0)
    abl = ablation_table(ps)
    return bl, abl


# ── step 8: view ranking & closed loop ────────────────────────────────────────
def step8_views(
    ps: pd.DataFrame,
    patches_df: pd.DataFrame,
    obs_df: pd.DataFrame,
    sem_df: pd.DataFrame,
    mat_df: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    print("\n[8/9] Ranking candidate views and running closed loop …")
    t0 = time.time()
    view_cfg = {"gap_threshold": 0.70, "max_target_patches": 30}
    candidates = generate_candidates(ps, view_cfg)
    if candidates.empty:
        print("  → no candidates generated")
        return pd.DataFrame(), pd.DataFrame()
    ranked = score_candidates(ps, candidates, view_cfg)
    print(f"  → {len(ranked):,} candidates scored, "
          f"top-1 value={ranked['value'].iloc[0]:.3f}  [{time.time()-t0:.1f}s]")

    # Build scene dict for closed-loop simulation
    scene = {
        "patches":      patches_df,
        "observations": obs_df.copy(),
        "semantics":    sem_df,
        "materials":    mat_df,
    }
    cl_cfg = {"steps": 10, "recovery_per_view": 0.75, "view": view_cfg}
    history_df, _, _ = run_closed_loop_from_scene(scene, cl_cfg)
    final_rr = history_df["recovery_rate"].iloc[-1] if len(history_df) > 0 else 0.0
    print(f"  → closed-loop 10-step final recovery={final_rr:.1%}")
    return ranked, history_df


# ── step 9: save + visualise ──────────────────────────────────────────────────
def step9_save(
    ps: pd.DataFrame,
    comp: pd.DataFrame,
    ranked: pd.DataFrame,
    history: pd.DataFrame,
    bl: pd.DataFrame,
    abl: pd.DataFrame,
) -> None:
    print("\n[9/9] Saving outputs …")
    tuned_rows = bl[bl["method"] == "Tuned patent score"]
    tuned = tuned_rows.iloc[0] if not tuned_rows.empty else None

    # Tables
    ps.to_csv(TABLES / f"patch_scores{SUFFIX}.csv", index=False)
    comp.to_csv(TABLES / f"component_ranking{SUFFIX}.csv", index=False)
    if not ranked.empty:
        ranked.to_csv(TABLES / f"candidate_view_ranking{SUFFIX}.csv", index=False)
    if not history.empty:
        history.to_csv(TABLES / f"closed_loop_results{SUFFIX}.csv", index=False)
    bl.to_csv(TABLES / f"baseline_results{SUFFIX}.csv", index=False)
    abl.to_csv(TABLES / f"ablation_results{SUFFIX}.csv", index=False)

    # Figures
    plot_patch_bars(ps, FIGURES / f"patch_gap_map{SUFFIX}.png")
    plot_component_ranking(comp, FIGURES / f"component_gap_map{SUFFIX}.png")
    if not history.empty:
        plot_closed_loop(history, FIGURES / f"closed_loop_curve{SUFFIX}.png")
    plot_baseline_results(bl, FIGURES / f"baseline_comparison{SUFFIX}.png")
    plot_ablation_results(abl, FIGURES / f"ablation_results{SUFFIX}.png")
    if not ranked.empty:
        plot_candidate_views(ranked, FIGURES / f"candidate_views{SUFFIX}.png")

    # Summary JSON
    summary = {
        "source":               "controlled_withheld_zone",
        "n_patches":            int(len(ps)),
        "n_elements":           int(ps["element_guid"].nunique()),
        "gt_missing_patches":   int(ps["gt_missing"].sum()),
        "gt_observed_patches":  int((~ps["gt_missing"]).sum()),
        "G_gap_mean":           float(ps["G_gap"].mean()),
        "G_gap_max":            float(ps["G_gap"].max()),
        "high_gap_pct":         float((ps["G_gap"] >= 0.55).mean()),
        "D_obs_mean":           float(ps["D_obs"].mean()),
        "D_geo_mean":           float(ps["D_geo"].mean()),
        "D_sem_valid_pct":      float(ps["D_sem"].notna().mean()),
        "D_sem_mean":           float(ps["D_sem"].dropna().mean()) if ps["D_sem"].notna().any() else None,
        "material_missing_rate": float(ps["D_mat_missing"].mean()),
        "material_conflict_rate": float(ps["D_mat_conflict"].mean()),
        "top1_view_value":      float(ranked["value"].iloc[0]) if not ranked.empty else None,
        "closed_loop_final_rr": float(history["recovery_rate"].iloc[-1]) if not history.empty else None,
        "Prevalence":           float(tuned["Prevalence"]) if tuned is not None else None,
        "AUROC":                float(tuned["AUROC"]) if tuned is not None else None,
        "AUPRC":                float(tuned["AUPRC"]) if tuned is not None else None,
        "AUPRC_lift":           float(tuned["AUPRC_lift"]) if tuned is not None else None,
        "F1":                   float(tuned["F1"]) if tuned is not None else None,
        "F1_threshold":         float(tuned["F1_threshold"]) if tuned is not None else None,
        "F1_oracle":            float(tuned["F1_oracle"]) if tuned is not None else None,
        "F1_oracle_threshold":  float(tuned["F1_oracle_threshold"]) if tuned is not None else None,
        "BalancedAccuracy":     float(tuned["BalancedAccuracy"]) if tuned is not None else None,
        "MCC":                  float(tuned["MCC"]) if tuned is not None else None,
    }
    (REPORTS / "synthetic_summary.json").write_text(json.dumps(summary, indent=2))
    print(f"  → summary: {REPORTS / 'synthetic_summary.json'}")

    # Print key results
    print("\n" + "═"*55)
    print("  SYNTHETIC SCAN RESULTS")
    print("═"*55)
    print(f"  Patches: {summary['n_patches']:,}  "
          f"(gt_missing={summary['gt_missing_patches']:,}, "
          f"observed={summary['gt_observed_patches']:,})")
    print(f"  G_gap: mean={summary['G_gap_mean']:.3f}, max={summary['G_gap_max']:.3f}")
    print(f"  D_sem valid: {summary['D_sem_valid_pct']:.1%}  "
          f"mean={summary['D_sem_mean']:.3f}" if summary['D_sem_mean'] else "  D_sem valid: 0%")
    if summary["AUROC"] is not None:
        print(f"  AUROC={summary['AUROC']:.4f}  AUPRC={summary['AUPRC']:.4f}  "
              f"F1={summary['F1']:.4f}")
    print("═"*55)


# ── main ───────────────────────────────────────────────────────────────────────
def main() -> None:
    t_total = time.time()

    elements_df = pd.read_parquet(PROCESSED / "ifc_elements.parquet")

    patches_df          = step1_patches()
    patches_df, _missing_ids = step3_gt_missing(patches_df)
    obs_df              = step2_evidence(patches_df, elements_df)
    sem_df              = step4_semantics(patches_df)
    mat_df              = step5_materials(patches_df, elements_df)
    ps, comp            = step6_gap(patches_df, obs_df, sem_df, mat_df)
    bl, abl             = step7_eval(ps)
    ranked, history     = step8_views(ps, patches_df, obs_df, sem_df, mat_df)
    step9_save(ps, comp, ranked, history, bl, abl)

    print(f"\nTotal time: {time.time()-t_total:.1f}s")


if __name__ == "__main__":
    main()
